/* ============================================================
   THE GEAR CATALOGUE, IN METRES - the light diagram's data.
   ------------------------------------------------------------
   Every item carries its real footprint seen from above, w x d,
   so the plan is to scale: a 90x120 softbox is 1.2 m of the
   grid and a light 2 m from the subject is 2 m. Nothing here is
   sized by eye, and nothing here is resized by hand.

   `beam` is the spread in degrees for things that throw light;
   `aim` says the item has a direction and must draw it; `fov`
   with `focal`, `frame` (long side of the image area, mm),
   `format` and `range` says it is a camera and draws its angle
   of view from its own frame - 80 mm is normal on 6 x 4.5 and a
   short telephoto on 35 mm.

   IT IS A .JS FILE AND NOT A .JSON ON PURPOSE. make-site.py
   lets a file travel only by kind, and .json is not a kind that
   travels - the one that did was build.json, and it leaked. The
   source of record is _notes/light-diagram/GEAR.json; this is
   that file, verbatim, wrapped in one constant. Edit the JSON
   and regenerate with _probe/ld-gear.py. Do not edit this file.
   ============================================================ */
const LD_GEAR = {
 "_comment": "THE CATALOGUE, IN METRES. Every item carries its real footprint seen from above, w x d, so the plan is to scale: a 90x120 softbox is 1.2m of the grid and a light 2m from the subject is 2m. Nothing here is sized by eye. `beam` is the spread in degrees for things that throw light; `aim` says the item has a direction and must draw it.",
 "grid": {
  "square": 0.5,
  "unit": "m",
  "room": [
   8,
   8
  ],
  "_note": "half-metre squares, an 8x8m room by default - a real studio"
 },
 "groups": [
  {
   "id": "subject",
   "name": "Subject",
   "items": [
    {
     "id": "person-standing",
     "name": "Person, standing",
     "w": 0.5,
     "d": 0.35,
     "aim": true
    },
    {
     "id": "person-seated",
     "name": "Person, seated",
     "w": 0.55,
     "d": 0.9,
     "aim": true
    },
    {
     "id": "head-shoulders",
     "name": "Head & shoulders",
     "w": 0.45,
     "d": 0.3,
     "aim": true
    },
    {
     "id": "still-life-table",
     "name": "Still-life table",
     "w": 1.2,
     "d": 0.8
    },
    {
     "id": "mannequin",
     "name": "Mannequin",
     "w": 0.45,
     "d": 0.3,
     "aim": true
    }
   ]
  },
  {
   "id": "camera",
   "name": "Camera",
   "items": [
    {
     "id": "cam-dslr",
     "name": "DSLR",
     "w": 0.16,
     "d": 0.14,
     "aim": true,
     "fov": true,
     "focal": 50,
     "format": "FF",
     "frame": 36,
     "range": [
      14,
      200
     ],
     "formats": [
      {
       "name": "FF",
       "frame": 36,
       "focal": 50,
       "range": [
        14,
        200
       ]
      },
      {
       "name": "APS-C",
       "frame": 23.6,
       "focal": 35,
       "range": [
        10,
        135
       ]
      },
      {
       "name": "MFT",
       "frame": 17.3,
       "focal": 25,
       "range": [
        7,
        100
       ]
      }
     ]
    },
    {
     "id": "cam-mirrorless",
     "name": "Mirrorless",
     "w": 0.13,
     "d": 0.11,
     "aim": true,
     "fov": true,
     "focal": 50,
     "format": "FF",
     "frame": 36,
     "range": [
      14,
      200
     ],
     "formats": [
      {
       "name": "FF",
       "frame": 36,
       "focal": 50,
       "range": [
        14,
        200
       ]
      },
      {
       "name": "APS-C",
       "frame": 23.6,
       "focal": 35,
       "range": [
        10,
        135
       ]
      },
      {
       "name": "MFT",
       "frame": 17.3,
       "focal": 25,
       "range": [
        7,
        100
       ]
      }
     ]
    },
    {
     "id": "cam-medium",
     "name": "Medium format",
     "w": 0.18,
     "d": 0.2,
     "aim": true,
     "fov": true,
     "focal": 80,
     "format": "6 \u00d7 4.5",
     "frame": 56,
     "range": [
      35,
      250
     ],
     "formats": [
      {
       "name": "6\u00d74.5",
       "frame": 56,
       "focal": 80,
       "range": [
        35,
        250
       ]
      },
      {
       "name": "6\u00d76",
       "frame": 56,
       "focal": 80,
       "range": [
        40,
        250
       ]
      },
      {
       "name": "6\u00d77",
       "frame": 70,
       "focal": 90,
       "range": [
        50,
        360
       ]
      },
      {
       "name": "6\u00d79",
       "frame": 84,
       "focal": 90,
       "range": [
        65,
        250
       ]
      }
     ]
    },
    {
     "id": "cam-view",
     "name": "Large format",
     "w": 0.3,
     "d": 0.35,
     "aim": true,
     "fov": true,
     "focal": 150,
     "format": "4\u00d75 in",
     "frame": 120,
     "range": [
      65,
      360
     ],
     "formats": [
      {
       "name": "4\u00d75 in",
       "frame": 120,
       "focal": 150,
       "range": [
        65,
        360
       ]
      },
      {
       "name": "8\u00d710 in",
       "frame": 254,
       "focal": 300,
       "range": [
        150,
        600
       ]
      }
     ]
    },
    {
     "id": "cam-phone",
     "name": "Phone",
     "w": 0.08,
     "d": 0.02,
     "aim": true,
     "fov": true,
     "focal": 26,
     "format": "35 mm equiv.",
     "frame": 36,
     "range": [
      13,
      77
     ]
    }
   ]
  },
  {
   "id": "light",
   "name": "Light",
   "items": [
    {
     "id": "strobe-bare",
     "name": "Strobe head, bare",
     "w": 0.2,
     "d": 0.3,
     "aim": true,
     "beam": 80
    },
    {
     "id": "softbox-60x90",
     "name": "Softbox 60 x 90",
     "w": 0.9,
     "d": 0.6,
     "aim": true,
     "beam": 60
    },
    {
     "id": "softbox-90x120",
     "name": "Softbox 90 x 120",
     "w": 1.2,
     "d": 0.9,
     "aim": true,
     "beam": 60
    },
    {
     "id": "octabox-95",
     "name": "Octabox 95",
     "w": 0.95,
     "d": 0.95,
     "aim": true,
     "beam": 60
    },
    {
     "id": "octabox-150",
     "name": "Octabox 150",
     "w": 1.5,
     "d": 1.5,
     "aim": true,
     "beam": 60
    },
    {
     "id": "stripbox-30x140",
     "name": "Strip box 30 x 140",
     "w": 1.4,
     "d": 0.3,
     "aim": true,
     "beam": 50
    },
    {
     "id": "beauty-dish-55",
     "name": "Beauty dish 55",
     "w": 0.55,
     "d": 0.55,
     "aim": true,
     "beam": 50
    },
    {
     "id": "beauty-dish-70",
     "name": "Beauty dish 70",
     "w": 0.7,
     "d": 0.7,
     "aim": true,
     "beam": 50
    },
    {
     "id": "umbrella-shoot-105",
     "name": "Umbrella, shoot-through 105",
     "w": 1.05,
     "d": 0.55,
     "aim": true,
     "beam": 90
    },
    {
     "id": "umbrella-reflect-105",
     "name": "Umbrella, reflective 105",
     "w": 1.05,
     "d": 0.55,
     "aim": true,
     "beam": 70
    },
    {
     "id": "umbrella-deep-165",
     "name": "Umbrella, deep 165",
     "w": 1.65,
     "d": 0.85,
     "aim": true,
     "beam": 60
    },
    {
     "id": "led-panel-30",
     "name": "LED panel 30 x 30",
     "w": 0.3,
     "d": 0.3,
     "aim": true,
     "beam": 60,
     "cont": true
    },
    {
     "id": "led-panel-60",
     "name": "LED panel 60 x 60",
     "w": 0.6,
     "d": 0.6,
     "aim": true,
     "beam": 60,
     "cont": true
    },
    {
     "id": "ring-light-45",
     "name": "Ring light 45",
     "w": 0.45,
     "d": 0.45,
     "aim": true,
     "beam": 70,
     "cont": true
    },
    {
     "id": "speedlight",
     "name": "Speedlight",
     "w": 0.08,
     "d": 0.12,
     "aim": true,
     "beam": 60
    },
    {
     "id": "tungsten-fresnel",
     "name": "Fresnel, tungsten",
     "w": 0.3,
     "d": 0.4,
     "aim": true,
     "beam": 30,
     "cont": true
    }
   ]
  },
  {
   "id": "shaping",
   "name": "Shaping",
   "items": [
    {
     "id": "barn-doors",
     "name": "Barn doors",
     "w": 0.25,
     "d": 0.25,
     "aim": true,
     "beam": 45
    },
    {
     "id": "grid",
     "name": "Grid",
     "w": 0.3,
     "d": 0.1,
     "aim": true,
     "beam": 20
    },
    {
     "id": "snoot",
     "name": "Snoot",
     "w": 0.15,
     "d": 0.25,
     "aim": true,
     "beam": 15
    },
    {
     "id": "gobo",
     "name": "Gobo",
     "w": 0.4,
     "d": 0.02,
     "aim": true,
     "solid": true
    },
    {
     "id": "flag-45x60",
     "name": "Flag 45 x 60",
     "w": 0.6,
     "d": 0.03,
     "aim": true,
     "solid": true
    },
    {
     "id": "flag-60x90",
     "name": "Flag 60 x 90",
     "w": 0.9,
     "d": 0.03,
     "aim": true,
     "solid": true
    },
    {
     "id": "scrim-100",
     "name": "Scrim 100 x 100",
     "w": 1.0,
     "d": 0.03,
     "aim": true
    },
    {
     "id": "diffusion-120x180",
     "name": "Diffusion 120 x 180",
     "w": 1.8,
     "d": 0.05,
     "aim": true
    }
   ]
  },
  {
   "id": "bounce",
   "name": "Bounce",
   "items": [
    {
     "id": "reflector-80-white",
     "name": "Reflector 80, white",
     "w": 0.8,
     "d": 0.05,
     "aim": true,
     "solid": true
    },
    {
     "id": "reflector-110-silver",
     "name": "Reflector 110, silver",
     "w": 1.1,
     "d": 0.05,
     "aim": true,
     "solid": true
    },
    {
     "id": "reflector-110-gold",
     "name": "Reflector 110, gold",
     "w": 1.1,
     "d": 0.05,
     "aim": true,
     "solid": true
    },
    {
     "id": "v-flat",
     "name": "V-flat",
     "w": 2.4,
     "d": 1.2,
     "aim": true,
     "solid": true
    },
    {
     "id": "bounce-board",
     "name": "Bounce board 100 x 150",
     "w": 1.5,
     "d": 0.05,
     "aim": true,
     "solid": true
    }
   ]
  },
  {
   "id": "room",
   "name": "Room",
   "items": [
    {
     "id": "wall",
     "name": "Wall",
     "w": 4.0,
     "d": 0.2,
     "tint": true,
     "stretch": true,
     "solid": true
    },
    {
     "id": "window",
     "name": "Window",
     "w": 1.4,
     "d": 0.2,
     "aim": true,
     "beam": 180,
     "cont": true
    },
    {
     "id": "doorway",
     "name": "Doorway",
     "w": 0.9,
     "d": 0.2
    },
    {
     "id": "curtain",
     "name": "Curtain",
     "w": 3.0,
     "d": 0.1,
     "tint": true,
     "stretch": true,
     "solid": true
    },
    {
     "id": "backdrop-272",
     "name": "Seamless roll 2.72 m",
     "w": 2.72,
     "d": 0.3,
     "tint": true,
     "sweep": true,
     "solid": true
    },
    {
     "id": "backdrop-135",
     "name": "Seamless roll 1.35 m",
     "w": 1.35,
     "d": 0.3,
     "tint": true,
     "sweep": true,
     "solid": true
    },
    {
     "id": "cyclorama",
     "name": "Cyclorama corner",
     "w": 4.0,
     "d": 4.0,
     "tint": true,
     "solid": true
    }
   ]
  },
  {
   "id": "support",
   "name": "Support",
   "items": [
    {
     "id": "light-stand",
     "name": "Light stand",
     "w": 1.0,
     "d": 1.0
    },
    {
     "id": "c-stand",
     "name": "C-stand",
     "w": 1.2,
     "d": 1.2
    },
    {
     "id": "boom",
     "name": "Boom arm",
     "w": 2.0,
     "d": 0.1,
     "aim": true
    },
    {
     "id": "tripod",
     "name": "Tripod",
     "w": 0.8,
     "d": 0.8
    }
   ]
  }
 ],
 "_frame_note": "Cameras carry `frame`, the long side of the image area in mm, and the angle of view is 2\u00b7atan(frame/2 \u00f7 focal): 80 mm on a 56 mm frame is a normal lens, 150 mm on 4x5 is a normal lens. `range` is the focal lengths that format is used with; `format` is the word printed beside the cone. The phone's focal is its 35 mm equivalent, so its frame is 36. Added 08-09-2026 at Batu's note. A camera may carry `formats`: the backs or film sizes that body takes, each with its own frame, normal focal and range; the chosen one is a setting on the placed camera (`m` in the string), not a separate item. Batu, 08-09: no separate cameras per format. DSLR and mirrorless carry three sensors: full frame (36), APS-C (23.6), Micro Four Thirds (17.3), each with its normal lens and range. Batu, 08-09.",
 "_tint_note": "`tint` items take a colour (RGB, `c` in the string); `sweep` items - the seamless rolls - take a length of paper pulled onto the floor (`l`, metres); the roll's width is the paper's and does not change. Lights take a gel colour the same way. Batu, 08-09.",
 "_stretch_note": "`stretch` items - a wall, a curtain - take a length (`w` in the string, metres); the studio's walls are not one length. Batu, 08-09.",
 "_cont_note": "`cont` marks a light that burns continuously (LED, tungsten, a window); the rest flash. A placed light can be told otherwise (`y` in the string). Batu, 08-09.",
 "_solid_note": "`solid` items stop light: a beam cone ends where it meets them and the shadow falls behind. Scrims and diffusion pass it; a window and a doorway are openings. Batu, 08-09."
};
